### ISSUE TITLE
miss external opencv and clapack for windows

### ISSUE THREAD

**Issue by tritq2** [sunglok/3dv_tutorial#1]
i tried to download and config again on visual studio 2013 but it not work. Can you give me your opencv and clapack folder in this tutorial?
My email: tranquoctri1995@gmail.com
Thanks a lot!

**Comment by sunglok** [comment]
Thank you for your comment. The link in README.md seems broken.
Please use the following URL.
https://github.com/sunglok/3dv_tutorial/releases/download/misc/EXTERNAL_for_Windows_32bit.zip

**Comment by tritq2** [comment]
Thank you so much :D
