### ISSUE TITLE
How to run the code in Ubuntu 18.04?

### ISSUE THREAD

**Issue by arjunskumar** [sunglok/3dv_tutorial#6]
Do you have any sample CMakelists.txt to make the source code?

**Comment by Albertcqq** [comment]
1.安装OpenCV3.4.7，CMake，Ceres1.14.0，安装2.0版本的Ceres会编译失败，不信可以试试，
参考博客：https://blog.csdn.net/qq_41586768/article/details/107541917

2.在CMakelists.txt里面加上
find_package(Ceres REQUIRED)
include_directories( ${OpenCV_INCLUDE_DIRS} ${Ceres_INCLUDE_DIRS})
在target_link_libraries这一行里面OpenCV_LIBRARIES后面加上 ${Ceres_LIBRARIES}，不然编译bundle_adjustmen_global.cpp时会失败。
参考博客：https://blog.csdn.net/qq_27452279/article/details/89947892

**Comment by arjunskumar** [comment]
Thanks @Albertcqq
